version: '3'
services:
  whoami:
    image: "traefik/whoami"
    container_name: "app-snippet"
    networks:
      - local
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.rule=Host(` ${WHOAMI_HOSTNAME} `)"
      - "traefik.http.routers.whoami.service=whoami"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
networks:
  proxy:
    external: true
  local:
    external: false
